### ISSUE TITLE
问题请教

### ISSUE THREAD

**Issue by greppro** [flowscolors/kube-eventer4j#1]
你好 看了您的开源项目 觉得您对阿里这个项目研究的比较深
我想咨询一下阿里开源的kube-events是怎么更换数据源的

**Comment by flowscolors** [comment]
你好 kube-eventer如果只是更换数据源只需要在其部署文件 https://github.com/AliyunContainerService/kube-eventer/blob/master/deploy/deploy.yaml 中更换command字段中的--sink参数即可，可配置多数据源，发mysql则配置mysql的sink，发kafka则配置kafka的sink。每种sink需要的参数在其docs文档目录中有写。

**Comment by greppro** [comment]
我是想在某个k8s集群去拉取另一个集群的事件信息 所以需要修改数据源 --source=kubernetes:https://kubernetes.default换成另一个集群的6443 但是不知道怎么认证

**Comment by flowscolors** [comment]
OK 明白你的意思了，这个kube-eventer确实是支持的，不过由于没给示例所以不好找，大致分两步。

1.把你需要监听的另一个集群的config文件映射到kube-eventer的容器里，你可以用configmap、secret映射或者直接打到镜像里。

2.在--source里面添加参数，变成 --source=kubernetes:https://your-another-master-ip:6443?inClusterConfig=false&auth=$ConfigPath 这个的$ConfigPath替换成你上一步容器里的路径。

这样kube-eventer启动的时候就会去找这个config文件做认证，连你的另外一个Kubernetes集群了。从而可以一个kube-eventer容器去监听多个Kubernetes的event。以上逻辑都在 kube-eventer仓库的 https://github.com/AliyunContainerService/kube-eventer/blob/master/common/kubernetes/configs.go 文件中。

**Comment by greppro** [comment]
刚刚实践了一下 成功了！ 趁热打铁 请教一下集群在告警中是怎么区分的呢 ？ 我用的是飞书的webhook 我看到在sink中有lablel的字段 但是没出现在我的告警中
![image](https://user-images.githubusercontent.com/46917564/146625648-b9166b23-d2c6-4e0d-907d-0b19843ece40.png)
![image](https://user-images.githubusercontent.com/46917564/146625659-84e66acd-a5dd-4def-a58f-7b54e68b8f2e.png)
![image](https://user-images.githubusercontent.com/46917564/146625679-ae6570c1-56e7-491c-80f9-63ce9c593044.png)

**Comment by flowscolors** [comment]
你好 我并未看到kube-eventer有sink支持label字段的功能。如果你找到了可以贴一个。

并且我个人认为目前的kube-eventer并不是天然支持这个功能。因为kube-eventer的目的是监听多个集群的event，往多个sink发送。假设真要实现“某一个event是哪个集群发出来的这个功能"，那应该在sources里面去配置，source里多传一个集群名的字段。而不是sink去加参数，因为sink设计上就是会收到多个集群的消息。并且现在的kube-eventer，source传的全是标准event对象，sink收到的也只会是标准event对象，并无法区分是哪个集群发出。

但是如果你的情况是只监听一个集群，并且想把这个集群名展示出来，那问题就简单很多。把其kube-eventer例子 https://github.com/AliyunContainerService/kube-eventer/blob/master/docs/en/webhook-sink.md  里的title的context换成对应集群名就好了。但是这并不是意味这sink知道了“某一个event是哪个集群发出来的“，只是把这个sink发出的所有event都换成了一个集群名。
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-webhook
  namespace: kube-system
data:
  content: '{
   "msg_type": "interactive",
   "card": {
      "config": {
         "wide_screen_mode": true,
         "enable_forward": true
      },
      "header": {
         "title": {
            "tag": "plain_text",
            "content": "$集群名"
         },
         "template": "Red"
      },
      "elements": [
         {
            "tag": "div",
            "text": {
               "tag": "lark_md",
               "content":  "**EventType:**  {{ .Type }}\n**EventKind:**  {{ .InvolvedObject.Kind }}\n**EventReason:**  {{ .Reason }}\n**EventTime:**  {{ .LastTimestamp }}\n**EventMessage:**  {{ .Message }}"
            }
        	}
      	]
   		}
		}'

```
如果你是有多个集群，并且就是要实现“某一个event是哪个集群发出来的“，那在使用现在的kube-eventer基础上，你需要保证你的event对象里面是带集群标签的，然后在上面的模板中新增一个字段来做event对象里集群字段的展示即可。

**Comment by greppro** [comment]
> 你好 我并未看到kube-eventer有sink支持label字段的功能。如果你找到了可以贴一个。
> 
> 并且我个人认为目前的kube-eventer并不是天然支持这个功能。因为kube-eventer的目的是监听多个集群的event，往多个sink发送。假设真要实现“某一个event是哪个集群发出来的这个功能"，那应该在sources里面去配置，source里多传一个集群名的字段。而不是sink去加参数，因为sink设计上就是会收到多个集群的消息。并且现在的kube-eventer，source传的全是标准event对象，sink收到的也只会是标准event对象，并无法区分是哪个集群发出。
> 
> 但是如果你的情况是只监听一个集群，并且想把这个集群名展示出来，那问题就简单很多。把其kube-eventer例子 https://github.com/AliyunContainerService/kube-eventer/blob/master/docs/en/webhook-sink.md 里的title的context换成对应集群名就好了。但是这并不是意味这sink知道了“某一个event是哪个集群发出来的“，只是把这个sink发出的所有event都换成了一个集群名。
> 
> ```
> apiVersion: v1
> kind: ConfigMap
> metadata:
>   name: custom-webhook
>   namespace: kube-system
> data:
>   content: '{
>    "msg_type": "interactive",
>    "card": {
>       "config": {
>          "wide_screen_mode": true,
>          "enable_forward": true
>       },
>       "header": {
>          "title": {
>             "tag": "plain_text",
>             "content": "$集群名"
>          },
>          "template": "Red"
>       },
>       "elements": [
>          {
>             "tag": "div",
>             "text": {
>                "tag": "lark_md",
>                "content":  "**EventType:**  {{ .Type }}\n**EventKind:**  {{ .InvolvedObject.Kind }}\n**EventReason:**  {{ .Reason }}\n**EventTime:**  {{ .LastTimestamp }}\n**EventMessage:**  {{ .Message }}"
>             }
>         	}
>       	]
>    		}
> 		}'
> ```
> 
> 如果你是有多个集群，并且就是要实现“某一个event是哪个集群发出来的“，那在使用现在的kube-eventer基础上，你需要保证你的event对象里面是带集群标签的，然后在上面的模板中新增一个字段来做event对象里集群字段的展示即可。

非常感谢! 现在已经用content来区分集群了  挺好用的
